# Data setup (step 1)
data_dir: /global/u1/r/rmastand/nsbi_for_dihiggs/data
morphing_setup: /global/u1/r/rmastand/nsbi_for_dihiggs/data/setup.h5

# MG generation (step 2)
madgraph:
    dir: /global/u1/r/rmastand/MG5_aMC_v3_5_1/
    n_runs: 25
    output_dir: /pscratch/sd/r/rmastand/hh_batching/mg_processes
    energy: 100

# Delphes (step 3)
delphes:
    input_dir_prefix: /pscratch/sd/r/rmastand/hh_batching/events_03_16/
    output_file: /pscratch/sd/r/rmastand/hh_batching/post_delphes_data/delphes
    long_term_storage_dir: /global/cfs/cdirs/m3246/rmastand/hh_prod/post_delphes_data
    
# Sampling (step 4)
sampling:
    input_dir: /global/cfs/cdirs/m3246/rmastand/hh_prod/post_delphes_data/
    output_dir: /global/cfs/cdirs/m3246/rmastand/hh_prod/samples/
    
# Plotting
plotting:
    fancy_name:
        c0: $c_{\phi}$
        c1: $c_{\phi d}$
        c2: $c_{t \phi}$
    color:
        c0: red
        c1: blue
        c2: green